package tonals.denpamake.model

enum class DenpaShape(val value: Byte, val text: String) {
    ROUND(
        (0x0).toByte(),
        "丸"
    ),
    ELLIPSE(
        (0x1).toByte(),
        "楕円"
    ),
    BALLOON(
        (0x2).toByte(),
        "風船"
    ),
    TRIANGLE(
        (0x3).toByte(),
        "三角"
    ),
    ONIGIRI(
        (0x4).toByte(),
        "おにぎり"
    ),
    RECTANGLE(
        (0x5).toByte(),
        "四角"
    ),
    SOAP(
        (0x6).toByte(),
        "せっけん"
    ),
    SLIME(
        (0x7).toByte(),
        "スライム"
    ),
    BIN(
        (0x8).toByte(),
        "ツボ"
    ),
    BEAR(
        (0x9).toByte(),
        "熊"
    ),
    WHIP(
        (0xA).toByte(),
        "ホイップ"
    ),
    TULIP(
        (0xB).toByte(),
        "チューリップ"
    ),
    LEMON(
        (0xC).toByte(),
        "レモン"
    ),
    SQUID(
        (0xD).toByte(),
        "イカ"
    ),
    ROCKET(
        (0xE).toByte(),
        "ロケット"
    ),
    STAR(
        (0xF).toByte(),
        "星"
    ),
    RAT(
        (0x10).toByte(),
        "ネズミ"
    ),
    HEART(
        (0x11).toByte(),
        "ハート"
    ),
    CAT(
        (0x12).toByte(),
        "猫"
    ),
    DEVIL(
        (0x13).toByte(),
        "悪魔"
    ),
    MOON(
        (0x14).toByte(),
        "月"
    ),
    DROP(
        (0x15).toByte(),
        "縦長しずく"
    ),
    HEADPHONE(
        (0x16).toByte(),
        "ヘッドホン"
    ),
    SPIKE(
        (0x17).toByte(),
        "とげ"
    ),
    EGG(
        (0x18).toByte(),
        "卵"
    ),
    TOWER(
        (0x19).toByte(),
        "塔"
    ),
    DOG(
        (0x1A).toByte(),
        "犬"
    ),
    FLAME(
        (0x1B).toByte(),
        "炎"
    ),
    BEETLE(
        (0x1C).toByte(),
        "クワガタ"
    ),
    SHINE(
        (0x1D).toByte(),
        "きらきら"
    ),
    HEXAGON(
        (0x1E).toByte(),
        "六角形"
    ),
    SUN(
        (0x1F).toByte(),
        "太陽"
    ),
    RABBIT(
        (0x20).toByte(),
        "うさ耳"
    ),
    RICE_CAKE(
        (0x21).toByte(),
        "鏡餅"
    ),
    FORTRESS(
        (0x22).toByte(),
        "砦"
    ),
    BLOCK(
        (0x23).toByte(),
        "ブロック"
    ),
    ONION(
        (0x24).toByte(),
        "玉ねぎ"
    ),
    SATURN(
        (0x25).toByte(),
        "土星"
    ),
    POT(
        (0x26).toByte(),
        "金魚鉢"
    ),
    FISH(
        (0x27).toByte(),
        "さかな"
    ),;

    companion object {
        private val map = values().associateBy { it.value }

        fun of(value: Byte): DenpaShape {
            return map[value] ?: ROUND
        }
    }
}